import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, CircleDot, Eye, LocateFixed, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/pages/../_core/hooks/useAuth";
import { startLogin } from "@/const";
import { CivicLogo } from "@/components/CivicLogo";

const steps = [
  { no: "01", label: "SEE IT", text: "Notice the issue before it becomes invisible.", icon: Eye, color: "#e9a86a" },
  { no: "02", label: "REPORT IT", text: "Give your community the context to act.", icon: CircleDot, color: "#a7cbb6" },
  { no: "03", label: "SUPPORT IT", text: "Add signal where the neighbourhood agrees.", icon: UsersRound, color: "#c7b9db" },
  { no: "04", label: "TRACK IT", text: "Follow the journey from report to resolution.", icon: LocateFixed, color: "#a6c8d2" },
];

export default function Home() {
  const { isAuthenticated } = useAuth();
  const [activeStep, setActiveStep] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActiveStep(v => (v + 1) % steps.length), 3200); return () => window.clearInterval(timer); }, []);
  return <div className="min-h-screen bg-[#f4f1e9] text-[#101a19]">
    <section className="relative min-h-[760px] overflow-hidden border-b border-[#d7d5ca]">
      <div className="aurora pointer-events-none absolute -inset-20 opacity-80"/><div className="bg-grid pointer-events-none absolute inset-0 opacity-70"/>
      <div className="relative mx-auto max-w-[1380px] px-5 pb-20 pt-10 lg:px-10 lg:pt-16">
        <div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><CivicLogo className="h-10 w-10" /><span className="font-display text-lg font-bold">Civic<span className="text-[#195c51]">X</span></span></Link><div className="flex items-center gap-2"><Link href="/map" className="hidden rounded-full px-4 py-2 text-sm font-semibold text-[#68736e] transition hover:bg-white/50 sm:block">Explore NCR</Link>{isAuthenticated ? <Link href="/profile" className="rounded-full border border-[#d7d5ca] bg-white/55 px-4 py-2 text-sm font-semibold">My profile</Link> : <><Link href="/register" className="hidden rounded-full px-4 py-2 text-sm font-semibold text-[#68736e] transition hover:bg-white/50 sm:block">Create account</Link><Button onClick={() => startLogin()} className="btn-primary rounded-full px-5">Sign in <ArrowUpRight size={15}/></Button></>}</div></div>
        <div className="grid items-center gap-10 pt-20 lg:grid-cols-[1fr_.93fr] lg:pt-28">
          <div className="fade-up max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d7d5ca] bg-white/55 px-3 py-1.5 text-xs font-bold tracking-[.2em] text-[#195c51]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#3c9a6e]"/> BUILT FOR THE NCR</div><h1 className="font-display text-[4rem] font-bold leading-[.9] tracking-[-.08em] sm:text-[6.5rem] lg:text-[8rem]">Civic<span className="text-[#195c51]">X</span></h1><p className="mt-8 max-w-xl text-2xl font-medium leading-tight tracking-[-.03em] sm:text-3xl">Turn local problems into <span className="text-[#195c51]">visible action.</span></p><p className="mt-5 max-w-lg text-base leading-7 text-[#68736e]">Report civic issues, discover problems around you, and track their journey from report to resolution.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/report/new" className="btn-primary inline-flex items-center gap-2 rounded-full px-6 py-3.5 font-semibold">Report an issue <ArrowUpRight size={17}/></Link><Link href="/map" className="inline-flex items-center gap-2 rounded-full border border-[#bdc6b9] bg-white/35 px-6 py-3.5 font-semibold transition hover:bg-white/70">Explore NCR <ArrowDownRight size={17}/></Link></div><div className="mt-9 flex items-center gap-3 text-sm text-[#68736e]"><ShieldCheck size={17} className="text-[#195c51]"/><span>Real records only. No invented civic data.</span></div></div>
          <div className="relative mx-auto w-full max-w-[570px] lg:justify-self-end"><div className="animate-floaty relative aspect-square rounded-[44px] border border-white/60 bg-[#e6decf]/50 p-5 shadow-[0_30px_100px_rgba(28,43,38,.18)] backdrop-blur-sm"><div className="map-surface h-full w-full rounded-[34px]"><div className="absolute left-[18%] top-[24%] h-32 w-44 rounded-[48%] border border-[#195c51]/20 bg-[#f7f5eb]/20"/><div className="absolute left-[50%] top-[20%] h-40 w-48 rounded-[48%] border border-[#195c51]/20 bg-[#f7f5eb]/20"/><div className="absolute bottom-[17%] left-[43%] h-28 w-52 rounded-[48%] border border-[#195c51]/20 bg-[#f7f5eb]/20"/><div className="map-route left-[8%] top-[61%] w-[76%] rotate-[14deg]"/><div className="map-route left-[35%] top-[20%] w-[65%] rotate-[76deg]"/><div className="absolute left-[45%] top-[45%] z-10"><div className="pulse-ring grid h-12 w-12 place-items-center rounded-full bg-[#195c51] text-white shadow-lg"><LocateFixed size={19}/></div></div><div className="absolute bottom-5 left-5 right-5 z-10 rounded-3xl border border-[#d7d5ca]/75 bg-[#f7f5eb]/85 p-4 backdrop-blur-md"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-[.16em] text-[#195c51]">LIVE NCR MAP</span><span className="rounded-full bg-[#e3efe6] px-2 py-1 text-[10px] font-bold text-[#3c7f5d]">EMPTY BY DESIGN</span></div><p className="mt-2 text-sm font-semibold">No reports found in this area yet.</p></div></div></div><div className="absolute -right-3 top-16 rounded-2xl border border-white/70 bg-white/70 px-4 py-3 shadow-xl backdrop-blur-md"><p className="text-[10px] font-bold tracking-[.18em] text-[#68736e]">COMMUNITY SIGNAL</p><p className="mt-1 font-display text-lg font-bold text-[#195c51]">starts with you</p></div><div className="absolute -bottom-5 -left-4 rounded-2xl border border-white/70 bg-[#195c51] px-4 py-3 text-white shadow-xl"><p className="text-[10px] font-bold tracking-[.18em] text-[#b7ded0]">REPORT → TRACK</p><p className="mt-1 font-display text-lg font-bold">one shared record</p></div></div>
        </div>
      </div>
    </section>
    <section className="border-b border-[#d7d5ca] bg-[#195c51] text-[#f4f1e9]"><div className="mx-auto flex max-w-[1380px] overflow-hidden px-5 lg:px-10"><div className="animate-marquee flex shrink-0 items-center gap-10 py-5 whitespace-nowrap text-xs font-bold tracking-[.3em] text-[#b7ded0]">{Array.from({length: 2}).flatMap((_, j) => ["REPORT", "LOCATE", "VERIFY", "PRIORITIZE", "TRACK", "RESOLVE", "ANALYSE"].map((x, i) => <span key={`${j}-${i}`} className="flex items-center gap-10">{x}<span className="text-[#e9a86a]">✦</span></span>))}</div></div></section>
    <section className="mx-auto max-w-[1380px] px-5 py-24 lg:px-10 lg:py-36"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="fade-up"><p className="text-xs font-bold tracking-[.28em] text-[#195c51]">WHY CIVICX</p><h2 className="mt-5 max-w-lg font-display text-4xl font-bold leading-tight tracking-[-.05em] md:text-6xl">A clearer signal for the places we share.</h2><p className="mt-6 max-w-md leading-7 text-[#68736e]">CivicX turns scattered observations into a shared, traceable record — without pretending the work is already done.</p></div><div className="grid gap-4 sm:grid-cols-2">{[{title:"Made for the moment", text:"Report from the street, with a location and the context only you can see.", icon:Eye}, {title:"Transparent by default", text:"Statuses, history, and community support stay legible from report to resolution.", icon:ShieldCheck}, {title:"Useful signal", text:"Priority is a documented indicator based on available issue and support data.", icon:Sparkles}, {title:"Private when needed", text:"Choose anonymous reporting while keeping secure ownership behind the scenes.", icon:UsersRound}].map((item, i) => <div key={item.title} className={`surface rounded-3xl p-6 fade-up stagger-${i+1}`}><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e5eee7] text-[#195c51]"><item.icon size={19}/></div><h3 className="mt-6 font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[#68736e]">{item.text}</p></div>)}</div></div></section>
    <section className="border-y border-[#d7d5ca] bg-[#ebe8de] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1380px]"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="text-xs font-bold tracking-[.28em] text-[#195c51]">THE CIVIC LOOP</p><h2 className="mt-5 font-display text-4xl font-bold tracking-[-.05em] md:text-6xl">From noticing to knowing.</h2></div><p className="max-w-sm text-sm leading-6 text-[#68736e]">Scroll through the loop. Every step earns its place in the record.</p></div><div className="mt-16 grid gap-5 md:grid-cols-4">{steps.map((step, i) => <button key={step.no} onClick={() => setActiveStep(i)} className={`group rounded-[28px] border p-6 text-left transition-all duration-300 ${activeStep === i ? "border-[#195c51] bg-[#f7f5eb] shadow-[0_20px_50px_rgba(28,43,38,.1)] md:-translate-y-3" : "border-[#d7d5ca] bg-transparent hover:bg-[#f7f5eb]/60"}`}><div className="flex items-center justify-between"><span className="font-display text-sm font-bold text-[#195c51]">{step.no}</span><span className="grid h-10 w-10 place-items-center rounded-2xl" style={{backgroundColor: step.color}}><step.icon size={18}/></span></div><p className="mt-12 text-xs font-bold tracking-[.22em] text-[#68736e]">{step.label}</p><h3 className="mt-3 font-display text-lg font-bold leading-snug">{step.text}</h3><ChevronRight className={`mt-8 transition ${activeStep === i ? "text-[#195c51]" : "text-[#b2b9b0]"}`} size={19}/></button>)}</div><div className="mt-12 flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-[#d8d8ce]"><div className="h-full rounded-full bg-[#195c51] transition-all duration-500" style={{width: `${((activeStep+1)/steps.length)*100}%`}}/></div><span className="font-display text-sm font-bold text-[#195c51]">{String(activeStep + 1).padStart(2,"0")} / {String(steps.length).padStart(2,"0")}</span></div></div></section>
    <section className="mx-auto max-w-[1380px] px-5 py-24 lg:px-10 lg:py-32"><div className="relative overflow-hidden rounded-[36px] bg-[#195c51] p-8 text-[#f7f5eb] md:p-14"><div className="absolute -right-20 -top-28 h-80 w-80 rounded-full border border-[#b7ded0]/25"/><div className="absolute -right-8 -top-16 h-56 w-56 rounded-full border border-[#b7ded0]/20"/><div className="relative max-w-2xl"><p className="text-xs font-bold tracking-[.28em] text-[#b7ded0]">START WHERE YOU ARE</p><h2 className="mt-5 font-display text-4xl font-bold leading-tight tracking-[-.05em] md:text-6xl">See a problem. Report it. Make your community heard.</h2><div className="mt-8 flex flex-wrap gap-3"><Link href="/report/new" className="inline-flex items-center gap-2 rounded-full bg-[#e9a86a] px-6 py-3.5 font-semibold text-[#28170b] transition hover:bg-[#f0b87b]">Report an issue <ArrowUpRight size={17}/></Link><Link href="/map" className="inline-flex items-center gap-2 rounded-full border border-[#b7ded0]/30 px-6 py-3.5 font-semibold text-[#f7f5eb] transition hover:bg-white/10">Explore NCR <ArrowUpRight size={17}/></Link></div></div></div></section>
    <footer className="border-t border-[#d7d5ca] px-5 py-10 lg:px-10"><div className="mx-auto flex max-w-[1380px] flex-col justify-between gap-5 text-sm text-[#68736e] md:flex-row"><span>© {new Date().getFullYear()} CivicX. Built for more visible communities.</span><div className="flex gap-5"><Link href="/settings" className="hover:text-[#195c51]">Settings</Link><Link href="/notifications" className="hover:text-[#195c51]">Notifications</Link><span className="flex items-center gap-1"><Check size={15} className="text-[#195c51]"/> Real data only</span></div></div></footer>
  </div>;
}
